import style from './style.module.css'

export function Promotion() {
    return (
        <div className={style.promotion}>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div> <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div> <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div> <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
           <div>
            <a>Привет</a>
           </div>
        </div>
    )   
}
